server:
    port: 9090

security:
    basic:
        enabled: false
token:
    secret: "nHaetaIDrFF8X4D2qc9L"

mongodb:
    host: "127.0.0.1"
    port: 27017
    db: "idema"

crud:
    collections:
        max_size: 90
            
--- #production
spring:
    profiles: production

server:
    port: 9090

security:
    basic:
        enabled: false
token:
    secret: "BvW9f8PDbR94pguJZiHl"
    
mongodb:
    host: "127.0.0.1"
    port: 27017
    db: "idema"

crud:
    collections:
        max_size: 100

--- #test
spring:
    profiles: test

server:
    port: 9090

security:
    basic:
        enabled: false
token:
    secret: "BvW9f8PDbR94pguJZiHl"

mongodb:
    host: "127.0.0.1"
    port: 27017
    db: "idema_test"

crud:
    collections:
        max_size: 20