server:
    port: 8090

security:
    basic:
        enabled: false
    user:
        password: "123"

mongodb:
    host: "127.0.0.1"
    port: 27017
    db: "idema"
            
--- #production
spring:
    profiles: production

server:
    port: 8090
    
mongodb:
    host: "127.0.0.1"
    port: 27017
    db: "idema"